name: ECS Fargate Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_URI: 811738710312.dkr.ecr.us-east-1.amazonaws.com/swathi-strapi

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t strapi-app:latest .

      # 4️⃣ Login to AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_URI

      # 5️⃣ Tag and Push Docker image
      - name: Tag & Push Docker image
        run: |
          docker tag strapi-app:latest $ECR_URI:latest
          docker push $ECR_URI:latest

      # 6️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      # 7️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init

      # 8️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve


